### ISSUE TITLE
After upgrading to 1.7.2 - TurboModule.h file not found

### ISSUE THREAD

**Issue by dimisus** [guhungry/react-native-photo-manipulator#931]
```
/node_modules/react-native-photo-manipulator/ios/generated/RNPhotoManipulatorSpecJSI.h:12:10: fatal error: 'ReactCommon/TurboModule.h' file not found
   12 | #include <ReactCommon/TurboModule.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

After upgrading to 1.7.2 this error above is thrown. 

Downgrading to 1.7.0 works.

**Comment by guhungry** [comment]
Hi @dimisus, ca i have more information?

1) what is your react native version
2) do you enable new architecture
3) can you try run `pod repo update && pod update`

**Comment by dimisus** [comment]
1. 0.72.17
2. Old architecture
3. Did 
```
rm -rf ~/Library/Caches/CocoaPods 
rm -rf Pods Podfile.lock
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod install
```

**Comment by Etaliya** [comment]
Any update?

**Comment by dimisus** [comment]
rn 0.75.3 seems to work with 1.7.2

**Comment by ansarikhurshid786** [comment]
same issue me using react native 0.64.4

**Comment by guhungry** [comment]
Hi @dimisus @Etaliya @ansarikhurshid786 ,

It should be fixed i version v1.7.3
